#!/bin/sh

module_name=`cat /module_name`
enable_wan_to_lan=$(config get enable_wan_to_lan)

stop()
{
	if [ "x$module_name" = "xLBR20" ]; then
		if [ "x$enable_wan_to_lan" = "x1" ]; then
			/usr/sbin/ssdk_sh debug phy set 0x3 0x0 0x1840   # set register 0x0  bit[11] to 1
		fi
		/usr/sbin/ssdk_sh debug phy set 0x4 0x0 0x1840   # set register 0x0  bit[11] to 1
		return
	elif [ "x$module_name" = "xRBS20" ]; then
		/usr/sbin/ssdk_sh debug phy set 0x3 0x0 0x1840   # set register 0x0  bit[11] to 1
		/usr/sbin/ssdk_sh debug phy set 0x4 0x0 0x1840   # set register 0x0  bit[11] to 1
		return
	fi

	if [ "x$module_name" = "xRBR50" -o "x$module_name" = "xRBR40" -o "x$module_name" = "xRBR30" ]; then
    	# /usr/sbin/ssdk_sh debug phy set 0x0 0x0 0x1840   # set register 0x0  bit[11] to 1
    	/usr/sbin/ssdk_sh debug phy set 0x1 0x0 0x1840   # set register 0x0  bit[11] to 1
    	/usr/sbin/ssdk_sh debug phy set 0x2 0x0 0x1840   # set register 0x0  bit[11] to 1
    	/usr/sbin/ssdk_sh debug phy set 0x3 0x0 0x1840   # set register 0x0  bit[11] to 1
    	# /usr/sbin/ssdk_sh debug phy set 0x4 0x0 0x1840   # set register 0x0  bit[11] to 1
    else
    	/usr/sbin/ssdk_sh debug phy set 0x0 0x0 0x1840   # set register 0x0  bit[11] to 1
	/usr/sbin/ssdk_sh debug phy set 0x1 0x0 0x1840   # set register 0x0  bit[11] to 1
	/usr/sbin/ssdk_sh debug phy set 0x2 0x0 0x1840   # set register 0x0  bit[11] to 1
	/usr/sbin/ssdk_sh debug phy set 0x3 0x0 0x1840   # set register 0x0  bit[11] to 1
	# /usr/sbin/ssdk_sh debug phy set 0x4 0x0 0x1840   # set register 0x0  bit[11] to 1
    fi
}

start()
{
	if [ "x$module_name" = "xLBR20" ]; then
		if [ "x$enable_wan_to_lan" = "x1" ]; then
			/usr/sbin/ssdk_sh debug phy set 0x3 0x0 0x1040  # set register 0x0  bit[11] to 0
		fi
    	 	/usr/sbin/ssdk_sh debug phy set 0x4 0x0 0x1040  # set register 0x0  bit[11] to 0
		return
	elif [ "x$module_name" = "xRBS20" ]; then
		/usr/sbin/ssdk_sh debug phy set 0x3 0x0 0x1040  # set register 0x0  bit[11] to 0
		/usr/sbin/ssdk_sh debug phy set 0x4 0x0 0x1040  # set register 0x0  bit[11] to 0
		return
	fi

	if [ "x$module_name" = "xRBR50" -o "x$module_name" = "xRBR40" -o "x$module_name" = "xRBR30" ]; then
    	# /usr/sbin/ssdk_sh debug phy set 0x0 0x0 0x1040  # set register 0x0  bit[11] to 0
    	/usr/sbin/ssdk_sh debug phy set 0x1 0x0 0x1040  # set register 0x0  bit[11] to 0
    	/usr/sbin/ssdk_sh debug phy set 0x2 0x0 0x1040  # set register 0x0  bit[11] to 0
    	/usr/sbin/ssdk_sh debug phy set 0x3 0x0 0x1040  # set register 0x0  bit[11] to 0
    	# /usr/sbin/ssdk_sh debug phy set 0x4 0x0 0x1040  # set register 0x0  bit[11] to 0
    else
    	/usr/sbin/ssdk_sh debug phy set 0x0 0x0 0x1040  # set register 0x0  bit[11] to 0
	/usr/sbin/ssdk_sh debug phy set 0x1 0x0 0x1040  # set register 0x0  bit[11] to 0
	/usr/sbin/ssdk_sh debug phy set 0x2 0x0 0x1040  # set register 0x0  bit[11] to 0
	/usr/sbin/ssdk_sh debug phy set 0x3 0x0 0x1040  # set register 0x0  bit[11] to 0
	# /usr/sbin/ssdk_sh debug phy set 0x4 0x0 0x1040  # set register 0x0  bit[11] to 0
    fi
}

restart()
{
    stop
    sleep 8
    start
}


restart
